[placeholders]
starter_type = { prompt = "Starter type", choices = ["Blinky", "Counter"], default = "Blinky", type = "string" }
gdb_enabled = { prompt = "Enable GDB", default = false, type = "bool" }
